version: 2

docker_defaults: &docker_defaults
  docker:
    - image: circleci/node:9.5

jobs:
  build:
    <<: *docker_defaults
    branches:
      ignore:
        - gh-pages
    steps:
      - checkout
      - run:
          name: Dependencies
          command: yarn
      - run:
          name: Flow typed
          command: yarn flow-typed
      - run:
          name: Temporary remove broken flow definitions
          command: rm flow-typed/npm/{react-redux_v5.x.x.js,redux_v3.x.x.js}
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Flow
          command: yarn flow --quiet
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build
          command: yarn dist:dir
      - run:
          name: Generate build stats
          command: "du -h dist | sort -h > /tmp/build-stats.txt"
      - store_artifacts:
          path: /tmp/build-stats.txt
          destination: build-stats.txt
