name: "Nightly | Sync Nightly Develop"
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  sync-branches:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop-nightly
          fetch-depth: 0
      - name: Set git
        run: |
          git config user.email "team-live@ledger.fr"
          git config user.name "Team Live"
      - name: Sync branches
        run: |
          git merge origin/develop
      - name: Sync changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop-nightly
          tags: false
          force: true
