name: tag nightly
on:
  schedule:
    - cron: "0 22 * * 1-5"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: check if current commit is on tag
        run: |
          git describe --exact-match &>/dev/null \
            && echo "You are on a tag. Exiting." \
            && exit 1 \
            || true
      - name: set git user
        run: |
          git config user.email "team-live@ledger.fr"
          git config user.name "Team Live"
      - name: get config
        run: |
          DATE=$(date '+%Y%m%dT%H%M')
          VERSION=$(grep version package.json | sed -E 's/.*: "(.*)",/\1/g' | cut -d '-' -f 1)
          COMMIT=$(git rev-parse HEAD)
          NIGHTLY=$VERSION-nightly.$DATE
          REMOTE=$(git config --get remote.origin.url)
          echo "::set-output name=nightly::$NIGHTLY"
          echo "::set-output name=commit::$COMMIT"
          echo "::set-output name=repo::$(basename $REMOTE .git)"
        id: config
      - name: new version with tag
        run: |
          yarn version --new-version ${{ steps.config.outputs.nightly }}
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
      - name: push tag
        run: |
          curl -s -X POST https://api.github.com/repos/LedgerHQ/${{ steps.config.outputs.repo }}/git/refs \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN_VAL }}" \
          -d @- << EOF
          {
            "ref": "refs/tags/${{ steps.config.outputs.nightly }}",
            "sha": "${{ steps.config.outputs.commit }}"
          }
          EOF
